/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "roman-numeral-calculator-test.check" instead.
 */

#include <check.h>

#line 1 "roman-numeral-calculator-test.check"
#include "roman-numeral-calculator.h"

START_TEST(roman_numeral_calculator_add_one_plus_one)
{
#line 4
	ck_assert_str_eq(add("I", "I"), "II");

}
END_TEST

START_TEST(roman_numeral_calculator_add_one_plus_two)
{
#line 7
	ck_assert_str_eq(add("I", "II"), "III");

}
END_TEST

START_TEST(roman_numeral_calculator_add_two_plus_two)
{
#line 10
	ck_assert_str_eq(add("II", "II"), "IV");

}
END_TEST

START_TEST(roman_numeral_calculator_add_two_plus_three)
{
#line 13
	ck_assert_str_eq(add("II", "III"), "V");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, roman_numeral_calculator_add_one_plus_one);
    tcase_add_test(tc1_1, roman_numeral_calculator_add_one_plus_two);
    tcase_add_test(tc1_1, roman_numeral_calculator_add_two_plus_two);
    tcase_add_test(tc1_1, roman_numeral_calculator_add_two_plus_three);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
