/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "roman-numeral-calculator-test.check" instead.
 */

#include <check.h>

#line 1 "roman-numeral-calculator-test.check"
#include "roman-numeral-calculator.h"

START_TEST(roma_numeral_calculator_add)
{
#line 4
	ck_assert_str_eq(add("I", "I"), "II");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, roma_numeral_calculator_add);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
